[package]
name = "spectrum-hid"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
spectrum-protocol = { path = "../spectrum-protocol" }
libc = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }

[dev-dependencies]
