[package]
name = "spectrum-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
spectrum-protocol = { path = "../spectrum-protocol" }
spectrum-hid = { path = "../spectrum-hid" }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }

[dev-dependencies]
